// flow-typed signature: 9e70d31a97d2e3b9d618ac99e5c17415
// flow-typed version: <<STUB>>/interpolate-html-plugin_v^2.0.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'interpolate-html-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'interpolate-html-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'interpolate-html-plugin/index' {
  declare module.exports: $Exports<'interpolate-html-plugin'>;
}
declare module 'interpolate-html-plugin/index.js' {
  declare module.exports: $Exports<'interpolate-html-plugin'>;
}
