// flow-typed signature: 3377567f8232cf91124a3f634149497b
// flow-typed version: <<STUB>>/request-ip_v^2.0.2/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request-ip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'request-ip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request-ip/examples/connect-middleware-custom' {
  declare module.exports: any;
}

declare module 'request-ip/examples/connect-middleware-simple' {
  declare module.exports: any;
}

declare module 'request-ip/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request-ip/examples/connect-middleware-custom.js' {
  declare module.exports: $Exports<'request-ip/examples/connect-middleware-custom'>;
}
declare module 'request-ip/examples/connect-middleware-simple.js' {
  declare module.exports: $Exports<'request-ip/examples/connect-middleware-simple'>;
}
declare module 'request-ip/index' {
  declare module.exports: $Exports<'request-ip'>;
}
declare module 'request-ip/index.js' {
  declare module.exports: $Exports<'request-ip'>;
}
declare module 'request-ip/test/index.js' {
  declare module.exports: $Exports<'request-ip/test/index'>;
}
